# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  lane :tests do
    run_tests(scheme: "WeatherAppTests",
            slack_url: "https://hooks.slack.com/services/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",
            slack_channel: "#ios-fastlane")
  end
end
